### PR TITLE
Async Fix

### PR DESCRIPTION
**Pull request by unSatisfied9**
Now displays message asynchronously on the MainWindow.Instance and waits
for it to be closed before continuing in the current function/method.

### CODE REVIEW

**Comment by madk** [comment]
Can you explain a bit more? I just tried the way it is and i don't see any error.

**Comment by unSatisfied9** [comment]
Sure, because this call is not awaited, execution of the current method continues before the call is completed. This doesn't matter as of now, however if you were to ever add any code beyond this method then it would not wait for the message to show and then disappear to execute.

**Comment by madk** [comment]
Oh, i thought that for some reason this would cause any error, i didn't awaited it because wasn't need at all since it's the end of the function. But i will merge it anyway.

**Comment by unSatisfied9** [comment]
Sounds good, I just prefer that await is there just in case someone ever adds anything below that in the future.

**Pull request merged**
